spring.application.name=rms-app

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/resource?currentSchema=rms
spring.datasource.username=rms
spring.datasource.password=rms

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.initialization-mode=always

spring.datasource.hikari.connection-init-sql=SET search_path TO rms


spring.mail.host=smtp.zoho.com
spring.mail.port=587
spring.mail.username=k.deepak@rudhrainfosolutions.com
spring.mail.password=Z46RmfsN1MkZ
spring.mail.properties.mail.smtp.pool=true
spring.mail.properties.mail.smtp.pool.size=4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.mail.properties.mail.smtp.quitwait=false
# Optional: avoid partial success reports
spring.mail.properties.mail.smtp.reportsuccess=false

storage.provider=D:/Resource_Management_RIS_Application/fileslocation

storage.default.provider=aws

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-part-count=300
aws.region=eu-north-1
aws.s3.bucket=rms-resume-bucket
aws.s3.base-url=https://rms-resume-bucket.s3.eu-north-1.amazonaws.com
aws.s3.enforce-sse=true
aws.access.key=AKIAUAW5NSG5HSZCAKEL
aws.secret.key=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
